# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon_server', '0002_auto_20170212_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoonepisodes',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
