# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon_server', '0003_auto_20170219_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoonepisodetoon',
            name='webtoon',
            field=models.ForeignKey(default=2222, on_delete=django.db.models.deletion.CASCADE, to='webtoon_server.Webtoon'),
            preserve_default=False,
        ),
    ]
